name: Build NextJS app & deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          script: |
            whoami
            echo "Actions was here"
            cd /var/www/anagrammy-frontend
            git pull
            yarn install
            yarn build
            yarn start