name: Build NextJS app & deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create the .ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh
      - name: Install the deploy key
        run: echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy && chmod 600 ~/.ssh/deploy
      - name: deploy the book
        run: ssh -i -tt ~/.ssh/deploy root@157.230.115.121
      # - name: Deploy
      #   run: |
      #     TEMP=$(mktemp)
      #     HOST=$(mktemp)
      #     USER=$(mktemp)
      #     echo "${{ secrets.SSH_KEY }}" > $TEMP
      #     echo "${{ secrets.SSH_HOST }}" > $HOST
      #     echo "${{ secrets.SSH_USERNAME }}" > $USER
      #     ssh -o 'StrictHostKeyChecking no' -i $TEMP root@157.230.115.121
      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@v0.1.2
      #   with:
      #     host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
      #     username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
      #     key: ${{ secrets.SSH_KEY }} # Private or public key of the server
      #     script: |
      #       whoami
